### ISSUE TITLE
多次触发回调函数问题

### ISSUE THREAD

**Issue by iamfish0120** [yujinpan/el-table-infinite-scroll#10]
## 运行环境
"element-ui": "^2.13.2",
"vue": "^2.6.11"
## 问题
当表格的数据太少，没法超过表格高度时，会重复触发回调函数，直到拼接完后的表格数据超过表格高度

**Comment by yujinpan** [comment]
请参考 https://element.eleme.cn/#/zh-CN/component/infiniteScroll#attributes 配置 `infinite-scroll-disabled` 或者 `infinite-scroll-immediate` 属性。
