### ISSUE TITLE
在使用ajax请求数据异步渲染时会触发两次加载数据方法....

### ISSUE THREAD

**Issue by ShinWG** [yujinpan/el-table-infinite-scroll#11]
![image](https://user-images.githubusercontent.com/12200308/99748418-78735a80-2b17-11eb-8f4c-df8105ff9aa4.png)

**Comment by yujinpan** [comment]
第一次加载完成是否撑满了表格的高度？

**Comment by ShinWG** [comment]
已经解决了. 设置异步前后更改disabled就可以了.
