### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zhanyi233** [yujinpan/el-table-infinite-scroll#5]
elInserted(scrollElem, binding, ...params);

const { distance, disabled } = getScrollOptions(el, vm);

这时候的getScrollOptions(el, vm); el 传值有误

**Comment by yujinpan** [comment]
感谢反馈，已经修复了，请更新版本至 v1.0.7 。

解决方案请查看：https://github.com/yujinpan/el-table-infinite-scroll/blob/07ff0a1beb087a9809a0f52dbe3326be83df0239/src/directives/table-infinite-scroll.js#L53
