### ISSUE TITLE
组件unbind报错

### ISSUE THREAD

**Issue by yj0zhang** [yujinpan/el-table-infinite-scroll#6]
![image](https://user-images.githubusercontent.com/9312245/71160305-48c22f80-2282-11ea-9143-ba9a48cb6c49.png)
unbind报错：

[Vue warn]: Error in directive el-table-infinite-scroll unbind hook: "TypeError: Cannot read property 'container' of undefined"

**Comment by yj0zhang** [comment]
知道原因了，我在el-table上面加了v-if，去掉就不会报错

**Comment by yujinpan** [comment]
👍 我会考虑兼容这个问题！
