### ISSUE TITLE
electron-vue中引入报错

### ISSUE THREAD

**Issue by ZhangZheng-GIS** [yujinpan/el-table-infinite-scroll#8]
![image](https://user-images.githubusercontent.com/14178404/76220886-2fae9680-6253-11ea-9f8c-7737d0cf0db9.png)

**Comment by yujinpan** [comment]
Hi，我在 electron-vue 中引入未发现报错，我的版本号：
![image](https://user-images.githubusercontent.com/20787785/77919431-c2c97200-72cf-11ea-8230-060c9871cd69.png)

**Comment by ZhangZheng-GIS** [comment]
@yujinpan  请问对element-ui的版本有要求吗？我用的2.11.1，用2.13.0会有问题

**Comment by yujinpan** [comment]
> 当我切换版本时确实出现了该报错信息。

Vue 以及 Vue 的 UI 组件需要额外的白名单配置，以至于 vue-loader 进行正常编译，参考官网说明：
https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals

具体配置：
```js
// .electron-vue/webpack.renderer.config.js
// 增加 el-table-infinite-scroll 与 element-ui
let whiteListedModules = ['vue', 'el-table-infinite-scroll', 'element-ui']
```
